out = (a for a in range(1, 15+1, 2))
print(out)
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
print(next(out), end=' ')
